# Generated by Django 3.0.1 on 2020-01-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_uidata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UVData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ivname', models.CharField(max_length=50)),
                ('ivd', models.CharField(max_length=50)),
                ('ivt', models.CharField(max_length=50)),
                ('ivp', models.CharField(max_length=50)),
                ('iV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.UVideo')),
                ('tt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.Teacher')),
            ],
        ),
    ]
